// frontend/angular/restaurant-front/src/app/restaurant-menu/restaurant-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '../../../node_modules/@angular/router';
import { PostService } from '../services/post.service';

@Component({
  selector: 'app-restaurant-menu',
  templateUrl: './restaurant-menu.component.html',
  styleUrls: ['./restaurant-menu.component.css']
})
export class RestaurantMenuComponent implements OnInit {
  restaurantId: number;
  restaurantMenu: any;
  constructor(private route: ActivatedRoute, private postService: PostService) {
  }

  ngOnInit() {
    let id = parseInt(this.route.snapshot.paramMap.get('id'));
    this.restaurantId = id;
    this.postService.getRestaurantMenu(id)
    .subscribe(
      (data: RestaurantMenuInterface) => {
        this.restaurantMenu = data;
      }
    );
  }

}

interface RestaurantMenuInterface {
  codigo: number;
  name: string;
  menuItems: any;
}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a href="/">Lista de Restaurantes</a><br>
      <a href="/restaurant/{{restaurantId}}/post">Adicionar items ao menu</a>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>{{restaurantMenu.name}}</h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Tipo</th>
            <th scope="col">Descrição</th>
            <th scope="col">Preço</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let item of restaurantMenu.menuItems">
            <td>{{item.name}}</td>
            <td>{{item.course}}</td>
            <td>{{item.description}}</td>
            <td>{{item.price}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

// frontend/react/restaurant-front/src/RestaurantList/RestaurantMenu.js
import React, { Component } from 'react';
import { Link } from 'react-router';


class RestaurantMenu extends Component {

    constructor(props) {
        super(props)
        this.state = {
            error: null,
            isLoaded: false,
            restaurant: {
                restaurantName: "",
                menuItems: []
            }
        }
    }

    componentDidMount() {
        fetch("http://localhost:8080/restaurantJson/" + this.props.params.id)
            .then(res => res.json())
            .then(
                (result) => {
                    console.log(result)
                    this.setState({
                        isLoaded: true,
                        restaurant: {
                            restaurantName: result.name,
                            menuItems: result.menuItems
                        }
                    });
                },
                (error) => {
                    this.setState({
                        isLoaded: true,
                        error
                    });
                }
            )
    }

    render() {
        const { error, isLoaded, restaurant } = this.state;
        if (error) {
            return <div>Error: {error.message}</div>
        } else if (!isLoaded) {
            return <div>Loading...</div>
        } else {
            return (
                <div className="container">
                    <div className="row">
                        <div className="col-md-12">
                            <Link to={"/restaurants"}>Lista de Restaurantes</Link>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-md-12">
                            <Link to={"/restaurant/" + this.props.params.id + "/menu/post"}>Adicionar item ao Menu</Link>
                        </div>
                    </div>
                    <hr />
                    <div className="row">
                        <div className="col-md-12">
                            <h1>{restaurant.restaurantName}</h1>
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Tipo</th>
                                        <th scope="col">Descrição</th>
                                        <th scope="col">Preço</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {restaurant.menuItems.map(item => (
                                        <tr key={item.codigo}>
                                            <td>{item.name}</td>
                                            <td>{item.course}</td>
                                            <td>{item.description}</td>
                                            <td>{item.price}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            )
        }

    }
}

export default RestaurantMenu
