// frontend/angular/restaurant-front/src/app/restaurant-post/restaurant-post.component.ts
import { Component, OnInit } from '@angular/core';
import { PostService } from '../services/post.service';
import { Router } from '../../../node_modules/@angular/router';

@Component({
  selector: 'app-restaurant-post',
  templateUrl: './restaurant-post.component.html',
  styleUrls: ['./restaurant-post.component.css']
})
export class RestaurantPostComponent implements OnInit {

  restaurants: any;
  constructor(private postService: PostService, private router: Router) { }

  ngOnInit() {
  }

  onPost(restaurantName) {
    const newRestaurant = {
      name: restaurantName
    };
    this.router.navigate(['']);
    //this.postService.postRestaurant(restaurantName);
    this.postService.postRestaurant(newRestaurant).subscribe(
      restaurant => this.restaurants.push(restaurant)
    );
  }

}



<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a href="/">Lista de Restaurantes</a>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <form>
        <label for="restaurantName">Nome do restaurante</label>
        <input #restaurantName (keyup)="0" type="text" class="form-control" id="restaurantName">
        <br>
        <button (click)="onPost(restaurantName.value)" class="btn btn-primary">Enviar</button>
      </form>
    </div>
  </div>
</div>

// frontend/react/restaurant-front/src/RestaurantList/RestaurantPost.js
import React, { Component } from "react";
import { Link } from 'react-router';
import { browserHistory } from 'react-router';

class RestaurantPost extends Component {
    constructor(props) {
        super(props)
        this.state = {
            restaurantName: ""
        }
    }

    postRestaurant() {
        fetch("http://localhost:8080/restaurantJson", {
            method: "POST",
            headers: {
                'Accept': "application/json",
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                name: this.state.restaurantName
            })
        })
        //console.log(this.state.restaurantName)
        browserHistory.push("/restaurants")
    }

    onHandleChange(event) {
        this.setState({
            restaurantName: event.target.value
        })
    }

    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col-md-12">
                        <Link to={"/restaurants"}>Lista de Restaurantes</Link>
                    </div>
                </div>
                <hr />
                <div className="row">
                    <div className="col-md-12">
                    <form>
                        <label htmlFor="restaurantName">Nome do Restaurante</label>
                    <input type="text" className="form-control" id="restaurantName" onChange={(event) => this.onHandleChange(event)} placeholder="Nome do restaurante" />
                    <br/>
                        <button onClick={this.postRestaurant.bind(this)} className="btn btn-primary">Enviar</button>
                    </form>
                       
                    </div>
                </div>
            </div>
        )
    }
}

export default RestaurantPost
