// frontend/angular/restaurant-front/src/app/restaurant-menu-post/restaurant-menu-post.component.ts
import { Component, OnInit } from '@angular/core';
import { PostService } from '../services/post.service';
import { ActivatedRoute, Router } from '../../../node_modules/@angular/router';

@Component({
  selector: 'app-restaurant-menu-post',
  templateUrl: './restaurant-menu-post.component.html',
  styleUrls: ['./restaurant-menu-post.component.css']
})
export class RestaurantMenuPostComponent implements OnInit {

  id: number;
  menuItems: any;
  constructor(private postService: PostService, private route: ActivatedRoute, private router: Router) { }

  ngOnInit() {
    this.id = parseInt(this.route.snapshot.paramMap.get('id'));
  }

  postRestaurantMenu(menuItemName, menuItemCourse, menuItemDescription, menuItemPrice) {
    const newRestaurantMenuItems = {
      name: menuItemName,
      course: menuItemCourse,
      description: menuItemDescription,
      price: parseFloat(menuItemPrice)
    };

    this.postService.postMenu(newRestaurantMenuItems, this.id).subscribe(
      menuItem => this.menuItems.push(menuItem)
    );
    this.router.navigate(['/restaurant/', this.id]);
  }

}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a href="/restaurant/{{id}}">Menu do Restaurante</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form>
        <div class="form-group">
          <label for="menuItemName">Nome</label>
          <input #menuItemName (keyup)="0" type="text" name="name" class="form-control" id="menuItemName" placeholder="Nome do item">
        </div>
        <div class="form-group">
          <label for="menuItemCourse">Tipo</label>
          <input #menuItemCourse (keyup)="0" type="text" name="course" class="form-control" id="menuItemCourse" placeholder="Tipo do item">
        </div>
        <div class="form-group">
          <label for="menuItemDescription">Descrição</label>
          <input #menuItemDescription (keyup)="0" type="text" name="description" class="form-control" id="menuItemDescription" placeholder="Descrição do item">
        </div>
        <div class="form-group">
          <label for="menuItemPrice">Preço</label>
          <input #menuItemPrice (keyup)="0" type="text" name="price" class="form-control" id="menuItemPrice" placeholder="Preço do item">
        <br>
        </div>
        <button (click)="postRestaurantMenu(menuItemName.value, menuItemCourse.value, menuItemDescription.value, menuItemPrice.value)" class="btn btn-primary">Enviar</button>
      </form>
    </div>
  </div>
</div>

// frontend/react/restaurant-front/src/RestaurantList/RestaurantMenuPost.js
import React, { Component } from 'react';
import { Link, browserHistory } from 'react-router';

class RestaurantMenuPost extends Component {

    constructor(props) {
        super(props)
        this.state = {
            name: "",
            course: "",
            description: "",
            price: 0.0
        }
        this.handleInputChange = this.handleInputChange.bind(this);
        this.postRestaurantMenu = this.postRestaurantMenu.bind(this);
    }

    postRestaurantMenu(event) {
        fetch("http://localhost:8080/restaurantJson/" + this.props.params.id + "/menu", {
            method: "POST",
            headers: {
                'Accept': "application/json",
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                name: this.state.name,
                course: this.state.course,
                description: this.state.description,
                price: this.state.price
            })
        })
        browserHistory.push("/restaurant/" + this.props.params.id)
    }

    handleInputChange(event) {
        const name = event.target.name
        this.setState({
            [name]: event.target.value
        })
    }
    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col-md-12">
                        <Link to={"/restaurant/" + this.props.params.id}>Menu do Restaurante</Link>
                    </div>
                </div>
                <hr/>
                <div className="row">
                    <div className="col-md-12">
                        <form method="post">
                            <div className="form-group">
                                <label htmlFor="menuItemName">Nome</label>
                                <input type="text" name="name" className="form-control" id="menuItemName" onChange={this.handleInputChange} placeholder="Nome do item" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="menuItemCourse">Tipo</label>
                                <input type="text" name="course" className="form-control" id="menuItemCourse" onChange={this.handleInputChange} placeholder="Tipo do item" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="menuItemDescription">Descrição</label>
                                <input type="text" name="description" className="form-control" id="menuItemDescription" onChange={this.handleInputChange} placeholder="Descrição do item" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="menuItemPrice">Preço</label>
                                <input type="text" name="price" className="form-control" id="menuItemPrice" onChange={this.handleInputChange} placeholder="Preço do item" />
                                <br/>
                            </div>
                            <button type="button" onClick={this.postRestaurantMenu} className="btn btn-primary">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        )
    }
}

export default RestaurantMenuPost
